/*DATAMIGRATION B891788E-0BE1-4858-86E9-F47884330F0A*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Demo', 'Food';
EXEC Rhetos.DataMigrationUse 'Demo', 'Food', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Demo', 'Food', 'Calories', 'integer';
EXEC Rhetos.DataMigrationUse 'Demo', 'Food', 'CaloriesNew', 'integer';
GO

UPDATE
    _Demo.Food
SET
    CaloriesNew = Calories
WHERE
    CaloriesNew IS NULL;

EXEC Rhetos.DataMigrationApplyMultiple 'Demo', 'Food', 'ID, CaloriesNew';